GET http://127.0.0.1:8000/products/ HTTP/1.1

###

GET http://127.0.0.1:8000/products/2/ HTTP/1.1

###

PUT http://127.0.0.1:8000/products/2/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgyMzgwMjQxLCJpYXQiOjE3ODIzNzk5NDEsImp0aSI6ImFiZmE2NDE1YzJhNjQ3YjViMmNmNWE1MGYxNDNkNGVkIiwidXNlcl9pZCI6MX0.Z1NcOkJJlkhYIsOjlYUq5Isd5MC-OMPnjpIOTFUUvck

{
    "name": "Television",
    "price": 300,
    "stock": 2,
    "description": "Ready for 55 inch screen TV"
}

###

DELETE http://127.0.0.1:8000/products/2/ HTTP/1.1

###

POST http://127.0.0.1:8000/products/ HTTP/1.1
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgyMzgwMjQxLCJpYXQiOjE3ODIzNzk5NDEsImp0aSI6ImFiZmE2NDE1YzJhNjQ3YjViMmNmNWE1MGYxNDNkNGVkIiwidXNlcl9pZCI6MX0.Z1NcOkJJlkhYIsOjlYUq5Isd5MC-OMPnjpIOTFUUvck

{
    "name": "Television1",
    "price": 300,
    "stock": 2,
    "description": "Ready for 55 inc screen TV"
}


###

POST http://127.0.0.1:8000/api/token/ HTTP/1.1
Content-Type: application/json 

{
    "username": "muzi",
    "password": "password"
}

###

POST http://127.0.0.1:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json 

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4MjM5NDAxNywiaWF0IjoxNzgyMzA3NjE3LCJqdGkiOiJhOTczZjViZDE2Mzc0NDQ5YWQ3MTJjN2IyYmY5Y2FlYSIsInVzZXJfaWQiOjF9.ZAqqF9ypmsB4kvxpLq6gpFZsq0b7ES160oGdhUzmAkY"
}



###
GET http://127.0.0.1:8000/user-orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgyNDY2NTIyLCJpYXQiOjE3ODI0NjYyMjIsImp0aSI6ImUyM2ZjMjQ4NzM4MjRhZmFiNTcxMWQzMmE2OWM5MGU5IiwidXNlcl9pZCI6Mn0.oMu5dcED0SHBTfm7HHMVUWmac6-L1c_yxy7HGqBrlFU
###
GET http://127.0.0.1:8000/orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgyNDY2NTczLCJpYXQiOjE3ODI0NjYyNzMsImp0aSI6IjI1MzBiM2RjYjk1MzRkN2VhODlhMWI2N2Q0OGMxZmEzIiwidXNlcl9pZCI6Mn0.q7m2icFPRbuGlbJW1XPmikGAYFEc07lhmwRR--LVT8o



###
POST http://127.0.0.1:8000/orders/ HTTP/1.1
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgyNDExNDM3LCJpYXQiOjE3ODI0MTExMzcsImp0aSI6IjRmNWZlZjU5MzdhZDQ1NGQ5ZmE1YzVkOTU5ZTc2NDcyIiwidXNlcl9pZCI6Mn0.0u0dh8sbRIh9TNl2A53Auk063fPPGzvO34N-0SlEYvY

{
    "status": "Pending",
    "items" : [
        {
        "product": 2,
        "quantity": 2
        },
        {
        "product": 3,
        "quantity": 1
        }
    ]
}


###
PUT http://127.0.0.1:8000/orders/aea7b635-ee3d-4f9b-b690-47ce0afae095/ HTTP/1.1
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgyNDEyMDQ3LCJpYXQiOjE3ODI0MTE3NDcsImp0aSI6Ijg4NjlhOGVhMTk2ZTQwNWZiMWRlMDc0MmQwODFmOTUzIiwidXNlcl9pZCI6Mn0.EgEDw-iBMqH6gr5ET3557xknRcYpS6kRH0QeJsm_z4s

{
    "status": "Pending",
    "items" : [
        {
        "product": 2,
        "quantity": 4
        },
        {
        "product": 3,
        "quantity": 1
        }
    ]
}


###

DELETE http://127.0.0.1:8000/orders/aea7b635-ee3d-4f9b-b690-47ce0afae095/ HTTP/1.1
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgyNDEyMDQ3LCJpYXQiOjE3ODI0MTE3NDcsImp0aSI6Ijg4NjlhOGVhMTk2ZTQwNWZiMWRlMDc0MmQwODFmOTUzIiwidXNlcl9pZCI6Mn0.EgEDw-iBMqH6gr5ET3557xknRcYpS6kRH0QeJsm_z4s
