FROM python:3.12

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

RUN set -e; \
    apt-get update && apt-get install -y --no-install-recommends \
        netcat-openbsd \
        gettext \
        httpie \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip && pip install flask

WORKDIR /code
COPY ./server.py /code/server.py

ENTRYPOINT ["python", "server.py"]